[book]
authors = ["RaySlash"]
language = "en"
multilingual = false
src = "src"
title = "NixCats Book"

[output.html]
cname = "nixcat-book"
git-repository-url = "https://github.com/rayslash/nixcats-book"
edit-url-template = "https://github.com/rayslash/nixcats-book/edit/master/{path}"

[rust]
edition = "2021"
